use_frameworks!

target 'LocalFileManager_Example' do
  pod 'LocalFileManager', :path => '../'

  target 'LocalFileManager_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
